server:
  port: 8081
spring:
  datasource:
    #    url: jdbc:mysql://10.4.66.80:3306/anti_transmission_yn?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/yunwei?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
dispatcher:
#  threadPoolSize: 2
#  task-info:
#    5: ["com.neusoft.logstore.dispatcher.service.DealService","com.neusoft.logstore.dispatcher.service.DealService"]
#    1: ["com.neusoft.logstore.dispatcher.service.DealService","com.neusoft.logstore.dispatcher.service.DealService"]
  quartzPoolSize: 2
  quartz-infos:
#    - cron: "0 0/2 * * * ? "
#      tasks: ["com.neusoft.yunwei.Task.CheckReport"]
    - cron: "0 0/1 * * * ? "
      tasks: ["com.neusoft.yunwei.Task.CompressionRatio"]